#!/usr/bin/env Rscript

usage='
Plot TSV data with ggplot from the command line.

Usage: ggcli [options] [TSV_FILE]

Options:
  -x COLNAME                  TSV column to use for x coords [default: x]
  -y COLNAME                  TSV column to use for y coords [default: y]
  -f --font-size FONTSIZE     base font size in pt [default: 18]
  -l --logy                   log scale the y axis
  -c COLNAME --color COLNAME  assign colors by COLNAME
  -o FILE --output FILE       output file (defaults to STDOUT)
  -t TITLE --title TITLE      title for plot [default: title]
'

suppressMessages(library(docopt))
suppressMessages(library(ggplot2))

# parse command line opts
opt = docopt(usage)

# input TSV data
if (!is.null(opt$TSV_FILE)) {
	data=read.delim(opt$TSV_FILE, header=TRUE)
} else {
	data=read.delim(file('stdin'),header=TRUE)
}

# output to STDOUT by default
if (is.null(opt$output)) {
	opt$output='|cat'
}
pdf(file=opt$output)

# aesthetics
font_size=as.numeric(opt$f)

mymapping = aes_string(x=opt$x, y=opt$y, color=opt$c)

p = ggplot(data, mapping=mymapping) +
	geom_line(size=1) +
	geom_point(size=3) +
	ggtitle(opt$title) +
	theme_grey(base_size=font_size)

if (opt$logy) {
	p = p + scale_y_log10()
}

print(p)
graphics.off()
